/*  isa-driver.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/

#include <linux/fs.h>
#include <linux/cdev.h>
#include <linux/uaccess.h>
#include <linux/errno.h>
#include <linux/irq.h>
#include <linux/irqdomain.h>

#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("isa-driver - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "isa-driver"

//定义主设备号 
static int major_num;
//定义class、device结构体
#define CLASS_NAME "isa_axi4lite"	
static struct class* gpio_class;    
static struct device* gpio_device;
static struct platform_device *global_pdev;
static void __iomem *leds; 

static int leds_drv_open(struct inode *Inode, struct file *File)
{
	//*leds = 0x0;				
	return 0;
}
 

static ssize_t leds_drv_read(struct file *file, char __user *buf, size_t offset, loff_t *ppos)
{
	unsigned int ret = 0;
	unsigned int tmp_val;
	
	tmp_val = *(volatile u32*)(leds + offset);
	ret = copy_to_user(buf, &tmp_val, sizeof(tmp_val));	
	
	return ret;
}
 
static ssize_t leds_drv_write(struct file *file, const char __user *buf, size_t offset, loff_t *ppos)
{
	unsigned int ret = 0;
	unsigned int tmp_val;
	
	ret = copy_from_user(&tmp_val, buf, sizeof(tmp_val));
	
	*(volatile u32*)(leds + offset) = tmp_val;	
	
	return ret;
}
 
//  描述与设备文件触发的事件对应的回调函数指针
static struct file_operations dev_fops =
{ 
	.owner = THIS_MODULE,
	.open = leds_drv_open,
	.read = leds_drv_read, 
	.write = leds_drv_write,
};

struct isa_driver_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

static irqreturn_t isa_driver_irq(int irq, void *lp)
{
	printk("isa-driver interrupt\n");
	return IRQ_HANDLED;
}

static int isa_driver_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct isa_driver_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct isa_driver_local *) kmalloc(sizeof(struct isa_driver_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate isa-driver device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "isa-driver: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "isa-driver at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &isa_driver_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"isa-driver at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);

	global_pdev = pdev;
	leds = lp->base_addr;
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int isa_driver_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct isa_driver_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	global_pdev = NULL;
	leds = NULL;
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id isa_driver_of_match[] = {
	{ .compatible = "xlnx,axi-isa-1.0", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, isa_driver_of_match);
#else
# define isa_driver_of_match
#endif


static struct platform_driver isa_driver_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= isa_driver_of_match,
	},
	.probe		= isa_driver_probe,
	.remove		= isa_driver_remove,
};

static int __init isa_driver_init(void)
{
	printk("<1>Hello module world.\n");
	//获取主设备号
	major_num = register_chrdev(0,DRIVER_NAME, &dev_fops);
	
	//创建设备类
	gpio_class = class_create(THIS_MODULE, CLASS_NAME);    

	if(IS_ERR(gpio_class))
	{                
	    	unregister_chrdev(major_num, DRIVER_NAME);
	    	printk(KERN_ALERT "Failed to register device class\n");
	    	return PTR_ERR(gpio_class);          
    	}
    	//注册设备
	gpio_device = device_create(gpio_class, NULL, MKDEV(major_num, 0), NULL, DRIVER_NAME);
	
	if(IS_ERR(gpio_device))
	{               
	    	class_destroy(gpio_class);           
	    	unregister_chrdev(major_num, DRIVER_NAME);
	    	printk(KERN_ALERT "Failed to create the device\n");
	    	return PTR_ERR(gpio_device);
	}
    	printk(KERN_INFO "LED_GPIO_init: device created correctly\n");

	return platform_driver_register(&isa_driver_driver);
}


static void __exit isa_driver_exit(void)
{
	//  删除设备文件,后创建的先卸载  
	device_destroy(gpio_class, MKDEV(major_num, 0));  
	class_destroy(gpio_class); 
	unregister_chrdev(major_num,DRIVER_NAME);	//释放设备号
	//  输出日志信息
	printk("LED_GPIO_exit success!\n");
	platform_driver_unregister(&isa_driver_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(isa_driver_init);
module_exit(isa_driver_exit);
