
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa[15]}]

set_property PACKAGE_PIN H16 [get_ports {isa_sa[0]}]
set_property PACKAGE_PIN H17 [get_ports {isa_sa[1]}]
set_property PACKAGE_PIN J18 [get_ports {isa_sa[2]}]
set_property PACKAGE_PIN H18 [get_ports {isa_sa[3]}]
set_property PACKAGE_PIN F19 [get_ports {isa_sa[4]}]
set_property PACKAGE_PIN F20 [get_ports {isa_sa[5]}]
set_property PACKAGE_PIN G17 [get_ports {isa_sa[6]}]
set_property PACKAGE_PIN G18 [get_ports {isa_sa[7]}]
set_property PACKAGE_PIN J20 [get_ports {isa_sa[8]}]
set_property PACKAGE_PIN H20 [get_ports {isa_sa[9]}]
set_property PACKAGE_PIN G19 [get_ports {isa_sa[10]}]
set_property PACKAGE_PIN G20 [get_ports {isa_sa[11]}]
set_property PACKAGE_PIN H15 [get_ports {isa_sa[12]}]
set_property PACKAGE_PIN G15 [get_ports {isa_sa[13]}]
set_property PACKAGE_PIN K14 [get_ports {isa_sa[14]}]
set_property PACKAGE_PIN J14 [get_ports {isa_sa[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in[15]}]

set_property PACKAGE_PIN N15 [get_ports {isa_sd_in[0]}]
set_property PACKAGE_PIN N16 [get_ports {isa_sd_in[1]}]
set_property PACKAGE_PIN L14 [get_ports {isa_sd_in[2]}]
set_property PACKAGE_PIN L15 [get_ports {isa_sd_in[3]}]
set_property PACKAGE_PIN M14 [get_ports {isa_sd_in[4]}]
set_property PACKAGE_PIN M15 [get_ports {isa_sd_in[5]}]
set_property PACKAGE_PIN K16 [get_ports {isa_sd_in[6]}]
set_property PACKAGE_PIN J16 [get_ports {isa_sd_in[7]}]
set_property PACKAGE_PIN J15 [get_ports {isa_sd_in[8]}]
set_property PACKAGE_PIN C20 [get_ports {isa_sd_in[9]}]
set_property PACKAGE_PIN B20 [get_ports {isa_sd_in[10]}]
set_property PACKAGE_PIN B19 [get_ports {isa_sd_in[11]}]
set_property PACKAGE_PIN A20 [get_ports {isa_sd_in[12]}]
set_property PACKAGE_PIN F16 [get_ports {isa_sd_in[13]}]
set_property PACKAGE_PIN F17 [get_ports {isa_sd_in[14]}]
set_property PACKAGE_PIN D19 [get_ports {isa_sd_in[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports dir_isa_sd1]
set_property PACKAGE_PIN D18 [get_ports dir_isa_sd1]

set_property IOSTANDARD LVCMOS33 [get_ports oe_isa_sd1]
set_property PACKAGE_PIN M19 [get_ports oe_isa_sd1]


set_property IOSTANDARD LVCMOS33 [get_ports isa_rst_drv]
set_property IOSTANDARD LVCMOS33 [get_ports isa_ior]
set_property IOSTANDARD LVCMOS33 [get_ports isa_iow]

set_property PACKAGE_PIN E18 [get_ports isa_iow]
set_property PACKAGE_PIN E19 [get_ports isa_ior]
set_property PACKAGE_PIN M20 [get_ports isa_rst_drv]

set_property IOSTANDARD LVCMOS33 [get_ports iocs16]
#set_property IOSTANDARD LVCMOS33 [get_ports sbhe]
set_property IOSTANDARD LVCMOS33 [get_ports irq5]

set_property PACKAGE_PIN E17 [get_ports iocs16]
#set_property PACKAGE_PIN N15 [get_ports sbhe]
set_property PACKAGE_PIN D20 [get_ports irq5]






set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sa_B[15]}]

set_property PACKAGE_PIN V20 [get_ports {isa_sa_B[0]}]
set_property PACKAGE_PIN W20 [get_ports {isa_sa_B[1]}]
set_property PACKAGE_PIN W19 [get_ports {isa_sa_B[2]}]
set_property PACKAGE_PIN N17 [get_ports {isa_sa_B[3]}]
set_property PACKAGE_PIN P18 [get_ports {isa_sa_B[4]}]
set_property PACKAGE_PIN Y19 [get_ports {isa_sa_B[5]}]
set_property PACKAGE_PIN N18 [get_ports {isa_sa_B[6]}]
set_property PACKAGE_PIN P19 [get_ports {isa_sa_B[7]}]
set_property PACKAGE_PIN R19 [get_ports {isa_sa_B[8]}]
set_property PACKAGE_PIN T19 [get_ports {isa_sa_B[9]}]
set_property PACKAGE_PIN T11 [get_ports {isa_sa_B[10]}]
set_property PACKAGE_PIN T10 [get_ports {isa_sa_B[11]}]
set_property PACKAGE_PIN T12 [get_ports {isa_sa_B[12]}]
set_property PACKAGE_PIN U12 [get_ports {isa_sa_B[13]}]
set_property PACKAGE_PIN U13 [get_ports {isa_sa_B[14]}]
set_property PACKAGE_PIN V13 [get_ports {isa_sa_B[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {isa_sd_in_B[15]}]

set_property PACKAGE_PIN V12 [get_ports {isa_sd_in_B[0]}]
set_property PACKAGE_PIN W13 [get_ports {isa_sd_in_B[1]}]
set_property PACKAGE_PIN T14 [get_ports {isa_sd_in_B[2]}]
set_property PACKAGE_PIN T15 [get_ports {isa_sd_in_B[3]}]
set_property PACKAGE_PIN P14 [get_ports {isa_sd_in_B[4]}]
set_property PACKAGE_PIN R14 [get_ports {isa_sd_in_B[5]}]
set_property PACKAGE_PIN Y16 [get_ports {isa_sd_in_B[6]}]
set_property PACKAGE_PIN Y17 [get_ports {isa_sd_in_B[7]}]
set_property PACKAGE_PIN W14 [get_ports {isa_sd_in_B[8]}]
set_property PACKAGE_PIN Y14 [get_ports {isa_sd_in_B[9]}]
set_property PACKAGE_PIN T16 [get_ports {isa_sd_in_B[10]}]
set_property PACKAGE_PIN U17 [get_ports {isa_sd_in_B[11]}]
set_property PACKAGE_PIN V15 [get_ports {isa_sd_in_B[12]}]
set_property PACKAGE_PIN W15 [get_ports {isa_sd_in_B[13]}]
set_property PACKAGE_PIN U14 [get_ports {isa_sd_in_B[14]}]
set_property PACKAGE_PIN U15 [get_ports {isa_sd_in_B[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports dir_isa_sd1_B]
set_property PACKAGE_PIN T20 [get_ports dir_isa_sd1_B]


set_property IOSTANDARD LVCMOS33 [get_ports oe_isa_sa1_B]
set_property PACKAGE_PIN U20 [get_ports oe_isa_sa1_B]


set_property IOSTANDARD LVCMOS33 [get_ports isa_rst_drv_B]
set_property IOSTANDARD LVCMOS33 [get_ports isa_ior_B]
set_property IOSTANDARD LVCMOS33 [get_ports isa_iow_B]

set_property PACKAGE_PIN U19 [get_ports isa_iow_B]
set_property PACKAGE_PIN N20 [get_ports isa_ior_B]
set_property PACKAGE_PIN W18 [get_ports isa_rst_drv_B]

set_property IOSTANDARD LVCMOS33 [get_ports iocs16_B]
#set_property IOSTANDARD LVCMOS33 [get_ports sbhe]
set_property IOSTANDARD LVCMOS33 [get_ports irq5_B]

set_property PACKAGE_PIN P20 [get_ports iocs16_B]
#set_property PACKAGE_PIN N15 [get_ports sbhe]
set_property PACKAGE_PIN U18 [get_ports irq5_B]
